// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	categoriesFieldNames          = builder.RawFieldNames(&Categories{})
	categoriesRows                = strings.Join(categoriesFieldNames, ",")
	categoriesRowsExpectAutoSet   = strings.Join(stringx.Remove(categoriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	categoriesRowsWithPlaceHolder = strings.Join(stringx.Remove(categoriesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCategoriesIdPrefix         = "cache:categories:id:"
	cacheCategoriesUserIdNamePrefix = "cache:categories:userId:name:"
)

type (
	categoriesModel interface {
		Insert(ctx context.Context, data *Categories) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Categories, error)
		FindOneByUserIdName(ctx context.Context, userId int64, name string) (*Categories, error)
		Update(ctx context.Context, data *Categories) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCategoriesModel struct {
		sqlc.CachedConn
		table string
	}

	Categories struct {
		Id        int64     `db:"id"`         // 主键ID
		UserId    int64     `db:"user_id"`    // 用户ID
		Name      string    `db:"name"`       // 分类名称
		Color     string    `db:"color"`      // 分类颜色
		CreatedAt time.Time `db:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at"` // 更新时间
	}
)

func newCategoriesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCategoriesModel {
	return &defaultCategoriesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`categories`",
	}
}

func (m *defaultCategoriesModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	categoriesIdKey := fmt.Sprintf("%s%v", cacheCategoriesIdPrefix, id)
	categoriesUserIdNameKey := fmt.Sprintf("%s%v:%v", cacheCategoriesUserIdNamePrefix, data.UserId, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, categoriesIdKey, categoriesUserIdNameKey)
	return err
}

func (m *defaultCategoriesModel) FindOne(ctx context.Context, id int64) (*Categories, error) {
	categoriesIdKey := fmt.Sprintf("%s%v", cacheCategoriesIdPrefix, id)
	var resp Categories
	err := m.QueryRowCtx(ctx, &resp, categoriesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", categoriesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoriesModel) FindOneByUserIdName(ctx context.Context, userId int64, name string) (*Categories, error) {
	categoriesUserIdNameKey := fmt.Sprintf("%s%v:%v", cacheCategoriesUserIdNamePrefix, userId, name)
	var resp Categories
	err := m.QueryRowIndexCtx(ctx, &resp, categoriesUserIdNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `name` = ? limit 1", categoriesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoriesModel) Insert(ctx context.Context, data *Categories) (sql.Result, error) {
	categoriesIdKey := fmt.Sprintf("%s%v", cacheCategoriesIdPrefix, data.Id)
	categoriesUserIdNameKey := fmt.Sprintf("%s%v:%v", cacheCategoriesUserIdNamePrefix, data.UserId, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, categoriesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Name, data.Color)
	}, categoriesIdKey, categoriesUserIdNameKey)
	return ret, err
}

func (m *defaultCategoriesModel) Update(ctx context.Context, newData *Categories) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	categoriesIdKey := fmt.Sprintf("%s%v", cacheCategoriesIdPrefix, data.Id)
	categoriesUserIdNameKey := fmt.Sprintf("%s%v:%v", cacheCategoriesUserIdNamePrefix, data.UserId, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, categoriesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.Name, newData.Color, newData.Id)
	}, categoriesIdKey, categoriesUserIdNameKey)
	return err
}

func (m *defaultCategoriesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCategoriesIdPrefix, primary)
}

func (m *defaultCategoriesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", categoriesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCategoriesModel) tableName() string {
	return m.table
}
