// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tasksFieldNames          = builder.RawFieldNames(&Tasks{})
	tasksRows                = strings.Join(tasksFieldNames, ",")
	tasksRowsExpectAutoSet   = strings.Join(stringx.Remove(tasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tasksRowsWithPlaceHolder = strings.Join(stringx.Remove(tasksFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTasksIdPrefix = "cache:tasks:id:"
)

type (
	tasksModel interface {
		Insert(ctx context.Context, data *Tasks) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Tasks, error)
		Update(ctx context.Context, data *Tasks) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTasksModel struct {
		sqlc.CachedConn
		table string
	}

	Tasks struct {
		Id          int64          `db:"id"`           // 主键ID
		UserId      int64          `db:"user_id"`      // 用户ID
		Title       string         `db:"title"`        // 任务标题
		Description sql.NullString `db:"description"`  // 任务描述
		Category    string         `db:"category"`     // 任务分类
		Priority    int64          `db:"priority"`     // 优先级(1:低,2:中,3:高)
		Status      int64          `db:"status"`       // 状态(0:未完成,1:已完成,2:已删除)
		DueDate     sql.NullTime   `db:"due_date"`     // 截止日期
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
		UpdatedAt   time.Time      `db:"updated_at"`   // 更新时间
		CompletedAt sql.NullTime   `db:"completed_at"` // 完成时间
	}
)

func newTasksModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTasksModel {
	return &defaultTasksModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tasks`",
	}
}

func (m *defaultTasksModel) Delete(ctx context.Context, id int64) error {
	tasksIdKey := fmt.Sprintf("%s%v", cacheTasksIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, tasksIdKey)
	return err
}

func (m *defaultTasksModel) FindOne(ctx context.Context, id int64) (*Tasks, error) {
	tasksIdKey := fmt.Sprintf("%s%v", cacheTasksIdPrefix, id)
	var resp Tasks
	err := m.QueryRowCtx(ctx, &resp, tasksIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tasksRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTasksModel) Insert(ctx context.Context, data *Tasks) (sql.Result, error) {
	tasksIdKey := fmt.Sprintf("%s%v", cacheTasksIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, tasksRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Description, data.Category, data.Priority, data.Status, data.DueDate, data.CompletedAt)
	}, tasksIdKey)
	return ret, err
}

func (m *defaultTasksModel) Update(ctx context.Context, data *Tasks) error {
	tasksIdKey := fmt.Sprintf("%s%v", cacheTasksIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tasksRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Title, data.Description, data.Category, data.Priority, data.Status, data.DueDate, data.CompletedAt, data.Id)
	}, tasksIdKey)
	return err
}

func (m *defaultTasksModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTasksIdPrefix, primary)
}

func (m *defaultTasksModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tasksRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTasksModel) tableName() string {
	return m.table
}
