// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package authservice

import (
	"context"

	"jike_todo/user/cmd/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthResponse          = user.AuthResponse
	ChangePasswordRequest = user.ChangePasswordRequest
	GetUserRequest        = user.GetUserRequest
	LoginRequest          = user.LoginRequest
	LogoutRequest         = user.LogoutRequest
	LogoutResponse        = user.LogoutResponse
	RefreshTokenRequest   = user.RefreshTokenRequest
	RegisterRequest       = user.RegisterRequest
	UpdateUserRequest     = user.UpdateUserRequest
	User                  = user.User
	ValidateTokenRequest  = user.ValidateTokenRequest

	AuthService interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
		RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*AuthResponse, error)
		Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
		ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*User, error)
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
		UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
		ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*User, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

func (m *defaultAuthService) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	client := user.NewAuthServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultAuthService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	client := user.NewAuthServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAuthService) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	client := user.NewAuthServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultAuthService) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	client := user.NewAuthServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultAuthService) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*User, error) {
	client := user.NewAuthServiceClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}

func (m *defaultAuthService) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	client := user.NewAuthServiceClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultAuthService) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	client := user.NewAuthServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultAuthService) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*User, error) {
	client := user.NewAuthServiceClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}
