// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AuthResp struct {
	User         UserInfo `json:"user"`
	AccessToken  string   `json:"access_token"`
	RefreshToken string   `json:"refresh_token"`
	ExpiresAt    int64    `json:"expires_at"`
}

type BaseResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data,omitempty"`
}

type BatchDeleteReq struct {
	TaskIDs []int64 `json:"task_ids" validate:"required,min=1"`
}

type BatchUpdateStatusReq struct {
	TaskIDs []int64 `json:"task_ids" validate:"required,min=1"`
	Status  int32   `json:"status" validate:"oneof=0 1"`
}

type CategoryInfo struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	Name      string `json:"name"`
	Color     string `json:"color"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type CategoryStat struct {
	Category string  `json:"category"`
	Count    int32   `json:"count"`
	Rate     float64 `json:"rate"`
}

type ChangePasswordReq struct {
	OldPassword string `json:"old_password" validate:"required"`
	NewPassword string `json:"new_password" validate:"required,min=6"`
}

type CreateCategoryReq struct {
	Name  string `json:"name" validate:"required,max=50"`
	Color string `json:"color,default=#1890ff"`
}

type CreateTaskReq struct {
	Title       string `json:"title" validate:"required,max=255"`
	Description string `json:"description,omitempty"`
	Category    string `json:"category,default=default"`
	Priority    int32  `json:"priority,default=1,oneof=1 2 3"`
	DueDate     string `json:"due_date,omitempty"`
}

type DayCompletion struct {
	Date      string `json:"date"`
	Completed int32  `json:"completed"`
	Total     int32  `json:"total"`
}

type GetTasksReq struct {
	Page     int32  `form:"page,default=1"`
	Size     int32  `form:"size,default=10"`
	Category string `form:"category,optional"`
	Status   int32  `form:"status,optional,oneof=0 1 2"`
	SortBy   string `form:"sort_by,default=created_at"`
}

type GetTasksResp struct {
	Tasks []TaskInfo `json:"tasks"`
	Total int32      `json:"total"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type PriorityStat struct {
	Priority int32   `json:"priority"`
	Count    int32   `json:"count"`
	Rate     float64 `json:"rate"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token" validate:"required"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required,min=3,max=50"`
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=6"`
	Nickname string `json:"nickname,omitempty" validate:"max=50"`
}

type SearchTasksReq struct {
	Keyword string `form:"keyword" validate:"required"`
	Page    int32  `form:"page,default=1"`
	Size    int32  `form:"size,default=10"`
}

type StatsCompletionResp struct {
	DailyCompletion []DayCompletion `json:"daily_completion"`
	CategoryStats   []CategoryStat  `json:"category_stats"`
	PriorityStats   []PriorityStat  `json:"priority_stats"`
}

type StatsOverviewResp struct {
	TotalTasks     int32   `json:"total_tasks"`
	CompletedTasks int32   `json:"completed_tasks"`
	PendingTasks   int32   `json:"pending_tasks"`
	CompletionRate float64 `json:"completion_rate"`
}

type TaskInfo struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Category    string `json:"category"`
	Priority    int32  `json:"priority"`
	Status      int32  `json:"status"`
	DueDate     string `json:"due_date"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
	CompletedAt string `json:"completed_at"`
}

type UpdateCategoryReq struct {
	Name  string `json:"name,optional" validate:"max=50"`
	Color string `json:"color,optional"`
}

type UpdateProfileReq struct {
	Nickname string `json:"nickname,omitempty" validate:"max=50"`
	Avatar   string `json:"avatar,omitempty"`
}

type UpdateTaskReq struct {
	Title       string `json:"title,optional" validate:"max=255"`
	Description string `json:"description,optional"`
	Category    string `json:"category,optional"`
	Priority    int32  `json:"priority,optional,oneof=1 2 3"`
	DueDate     string `json:"due_date,optional"`
}

type UpdateTaskStatusReq struct {
	Status int32 `json:"status" validate:"oneof=0 1"`
}

type UserInfo struct {
	ID          int64  `json:"id"`
	Username    string `json:"username"`
	Email       string `json:"email"`
	Nickname    string `json:"nickname"`
	Avatar      string `json:"avatar"`
	Status      int32  `json:"status"`
	LastLoginAt string `json:"last_login_at"`
	CreatedAt   string `json:"created_at"`
}
