// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: task.proto

package server

import (
	"context"

	"jike_todo/task/cmd/rpc/internal/logic"
	"jike_todo/task/cmd/rpc/internal/svc"
	"jike_todo/task/cmd/rpc/task"
)

type TaskServiceServer struct {
	svcCtx *svc.ServiceContext
	task.UnimplementedTaskServiceServer
}

func NewTaskServiceServer(svcCtx *svc.ServiceContext) *TaskServiceServer {
	return &TaskServiceServer{
		svcCtx: svcCtx,
	}
}

// Task CRUD operations
func (s *TaskServiceServer) CreateTask(ctx context.Context, in *task.CreateTaskRequest) (*task.Task, error) {
	l := logic.NewCreateTaskLogic(ctx, s.svcCtx)
	return l.CreateTask(in)
}

func (s *TaskServiceServer) GetTask(ctx context.Context, in *task.GetTaskRequest) (*task.Task, error) {
	l := logic.NewGetTaskLogic(ctx, s.svcCtx)
	return l.GetTask(in)
}

func (s *TaskServiceServer) GetTasks(ctx context.Context, in *task.GetTasksRequest) (*task.GetTasksResponse, error) {
	l := logic.NewGetTasksLogic(ctx, s.svcCtx)
	return l.GetTasks(in)
}

func (s *TaskServiceServer) UpdateTask(ctx context.Context, in *task.UpdateTaskRequest) (*task.Task, error) {
	l := logic.NewUpdateTaskLogic(ctx, s.svcCtx)
	return l.UpdateTask(in)
}

func (s *TaskServiceServer) DeleteTask(ctx context.Context, in *task.DeleteTaskRequest) (*task.DeleteTaskResponse, error) {
	l := logic.NewDeleteTaskLogic(ctx, s.svcCtx)
	return l.DeleteTask(in)
}

func (s *TaskServiceServer) UpdateTaskStatus(ctx context.Context, in *task.UpdateTaskStatusRequest) (*task.Task, error) {
	l := logic.NewUpdateTaskStatusLogic(ctx, s.svcCtx)
	return l.UpdateTaskStatus(in)
}

// Search functionality
func (s *TaskServiceServer) SearchTasks(ctx context.Context, in *task.SearchTasksRequest) (*task.SearchTasksResponse, error) {
	l := logic.NewSearchTasksLogic(ctx, s.svcCtx)
	return l.SearchTasks(in)
}

// Category operations
func (s *TaskServiceServer) CreateCategory(ctx context.Context, in *task.CreateCategoryRequest) (*task.Category, error) {
	l := logic.NewCreateCategoryLogic(ctx, s.svcCtx)
	return l.CreateCategory(in)
}

func (s *TaskServiceServer) GetCategories(ctx context.Context, in *task.GetCategoriesRequest) (*task.GetCategoriesResponse, error) {
	l := logic.NewGetCategoriesLogic(ctx, s.svcCtx)
	return l.GetCategories(in)
}

func (s *TaskServiceServer) UpdateCategory(ctx context.Context, in *task.UpdateCategoryRequest) (*task.Category, error) {
	l := logic.NewUpdateCategoryLogic(ctx, s.svcCtx)
	return l.UpdateCategory(in)
}

func (s *TaskServiceServer) DeleteCategory(ctx context.Context, in *task.DeleteCategoryRequest) (*task.DeleteCategoryResponse, error) {
	l := logic.NewDeleteCategoryLogic(ctx, s.svcCtx)
	return l.DeleteCategory(in)
}

// Statistics operations
func (s *TaskServiceServer) GetStatsOverview(ctx context.Context, in *task.GetStatsRequest) (*task.GetStatsOverviewResponse, error) {
	l := logic.NewGetStatsOverviewLogic(ctx, s.svcCtx)
	return l.GetStatsOverview(in)
}

func (s *TaskServiceServer) GetStatsCompletion(ctx context.Context, in *task.GetStatsRequest) (*task.GetStatsCompletionResponse, error) {
	l := logic.NewGetStatsCompletionLogic(ctx, s.svcCtx)
	return l.GetStatsCompletion(in)
}

// Batch operations
func (s *TaskServiceServer) BatchUpdateStatus(ctx context.Context, in *task.BatchUpdateStatusRequest) (*task.BatchUpdateStatusResponse, error) {
	l := logic.NewBatchUpdateStatusLogic(ctx, s.svcCtx)
	return l.BatchUpdateStatus(in)
}

func (s *TaskServiceServer) BatchDelete(ctx context.Context, in *task.BatchDeleteRequest) (*task.BatchDeleteResponse, error) {
	l := logic.NewBatchDeleteLogic(ctx, s.svcCtx)
	return l.BatchDelete(in)
}
