// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"jike_todo/user/cmd/rpc/internal/logic"
	"jike_todo/user/cmd/rpc/internal/svc"
	"jike_todo/user/cmd/rpc/user"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.AuthResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AuthServiceServer) Login(ctx context.Context, in *user.LoginRequest) (*user.AuthResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AuthServiceServer) RefreshToken(ctx context.Context, in *user.RefreshTokenRequest) (*user.AuthResponse, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *AuthServiceServer) Logout(ctx context.Context, in *user.LogoutRequest) (*user.LogoutResponse, error) {
	l := logic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

func (s *AuthServiceServer) ValidateToken(ctx context.Context, in *user.ValidateTokenRequest) (*user.User, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

func (s *AuthServiceServer) GetUser(ctx context.Context, in *user.GetUserRequest) (*user.User, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *AuthServiceServer) UpdateUser(ctx context.Context, in *user.UpdateUserRequest) (*user.User, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *AuthServiceServer) ChangePassword(ctx context.Context, in *user.ChangePasswordRequest) (*user.User, error) {
	l := logic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}
