// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"jike_todo/gateway/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// User login
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				// Refresh token
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: RefreshTokenHandler(serverCtx),
			},
			{
				// User registration
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Logout
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: LogoutHandler(serverCtx),
			},
			{
				// Create category
				Method:  http.MethodPost,
				Path:    "/categories",
				Handler: CreateCategoryHandler(serverCtx),
			},
			{
				// Get category list
				Method:  http.MethodGet,
				Path:    "/categories",
				Handler: GetCategoriesHandler(serverCtx),
			},
			{
				// Update category
				Method:  http.MethodPut,
				Path:    "/categories/:id",
				Handler: UpdateCategoryHandler(serverCtx),
			},
			{
				// Delete category
				Method:  http.MethodDelete,
				Path:    "/categories/:id",
				Handler: DeleteCategoryHandler(serverCtx),
			},
			{
				// Get completion statistics
				Method:  http.MethodGet,
				Path:    "/stats/completion",
				Handler: GetStatsCompletionHandler(serverCtx),
			},
			{
				// Get overview statistics
				Method:  http.MethodGet,
				Path:    "/stats/overview",
				Handler: GetStatsOverviewHandler(serverCtx),
			},
			{
				// Create task
				Method:  http.MethodPost,
				Path:    "/tasks",
				Handler: CreateTaskHandler(serverCtx),
			},
			{
				// Get task list
				Method:  http.MethodGet,
				Path:    "/tasks",
				Handler: GetTasksHandler(serverCtx),
			},
			{
				// Get task detail
				Method:  http.MethodGet,
				Path:    "/tasks/:id",
				Handler: GetTaskHandler(serverCtx),
			},
			{
				// Update task
				Method:  http.MethodPut,
				Path:    "/tasks/:id",
				Handler: UpdateTaskHandler(serverCtx),
			},
			{
				// Delete task
				Method:  http.MethodDelete,
				Path:    "/tasks/:id",
				Handler: DeleteTaskHandler(serverCtx),
			},
			{
				// Update task status
				Method:  http.MethodPatch,
				Path:    "/tasks/:id/status",
				Handler: UpdateTaskStatusHandler(serverCtx),
			},
			{
				// Batch delete tasks
				Method:  http.MethodDelete,
				Path:    "/tasks/batch",
				Handler: BatchDeleteTasksHandler(serverCtx),
			},
			{
				// Batch update task status
				Method:  http.MethodPatch,
				Path:    "/tasks/batch/status",
				Handler: BatchUpdateTaskStatusHandler(serverCtx),
			},
			{
				// Search tasks
				Method:  http.MethodGet,
				Path:    "/tasks/search",
				Handler: SearchTasksHandler(serverCtx),
			},
			{
				// Change password
				Method:  http.MethodPut,
				Path:    "/user/password",
				Handler: ChangePasswordHandler(serverCtx),
			},
			{
				// Get user profile
				Method:  http.MethodGet,
				Path:    "/user/profile",
				Handler: GetProfileHandler(serverCtx),
			},
			{
				// Update user profile
				Method:  http.MethodPut,
				Path:    "/user/profile",
				Handler: UpdateProfileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
