// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: task.proto

package taskservice

import (
	"context"

	"jike_todo/task/cmd/rpc/task"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchDeleteRequest         = task.BatchDeleteRequest
	BatchDeleteResponse        = task.BatchDeleteResponse
	BatchUpdateStatusRequest   = task.BatchUpdateStatusRequest
	BatchUpdateStatusResponse  = task.BatchUpdateStatusResponse
	Category                   = task.Category
	CategoryStat               = task.CategoryStat
	CreateCategoryRequest      = task.CreateCategoryRequest
	CreateTaskRequest          = task.CreateTaskRequest
	DailyCompletion            = task.DailyCompletion
	DeleteCategoryRequest      = task.DeleteCategoryRequest
	DeleteCategoryResponse     = task.DeleteCategoryResponse
	DeleteTaskRequest          = task.DeleteTaskRequest
	DeleteTaskResponse         = task.DeleteTaskResponse
	GetCategoriesRequest       = task.GetCategoriesRequest
	GetCategoriesResponse      = task.GetCategoriesResponse
	GetStatsCompletionResponse = task.GetStatsCompletionResponse
	GetStatsOverviewResponse   = task.GetStatsOverviewResponse
	GetStatsRequest            = task.GetStatsRequest
	GetTaskRequest             = task.GetTaskRequest
	GetTasksRequest            = task.GetTasksRequest
	GetTasksResponse           = task.GetTasksResponse
	PriorityStat               = task.PriorityStat
	SearchTasksRequest         = task.SearchTasksRequest
	SearchTasksResponse        = task.SearchTasksResponse
	Task                       = task.Task
	UpdateCategoryRequest      = task.UpdateCategoryRequest
	UpdateTaskRequest          = task.UpdateTaskRequest
	UpdateTaskStatusRequest    = task.UpdateTaskStatusRequest

	TaskService interface {
		// Task CRUD operations
		CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error)
		GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
		GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksResponse, error)
		UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Task, error)
		DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error)
		UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusRequest, opts ...grpc.CallOption) (*Task, error)
		// Search functionality
		SearchTasks(ctx context.Context, in *SearchTasksRequest, opts ...grpc.CallOption) (*SearchTasksResponse, error)
		// Category operations
		CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*Category, error)
		GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
		UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*Category, error)
		DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
		// Statistics operations
		GetStatsOverview(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsOverviewResponse, error)
		GetStatsCompletion(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsCompletionResponse, error)
		// Batch operations
		BatchUpdateStatus(ctx context.Context, in *BatchUpdateStatusRequest, opts ...grpc.CallOption) (*BatchUpdateStatusResponse, error)
		BatchDelete(ctx context.Context, in *BatchDeleteRequest, opts ...grpc.CallOption) (*BatchDeleteResponse, error)
	}

	defaultTaskService struct {
		cli zrpc.Client
	}
)

func NewTaskService(cli zrpc.Client) TaskService {
	return &defaultTaskService{
		cli: cli,
	}
}

// Task CRUD operations
func (m *defaultTaskService) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.CreateTask(ctx, in, opts...)
}

func (m *defaultTaskService) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.GetTask(ctx, in, opts...)
}

func (m *defaultTaskService) GetTasks(ctx context.Context, in *GetTasksRequest, opts ...grpc.CallOption) (*GetTasksResponse, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.GetTasks(ctx, in, opts...)
}

func (m *defaultTaskService) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.UpdateTask(ctx, in, opts...)
}

func (m *defaultTaskService) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.DeleteTask(ctx, in, opts...)
}

func (m *defaultTaskService) UpdateTaskStatus(ctx context.Context, in *UpdateTaskStatusRequest, opts ...grpc.CallOption) (*Task, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.UpdateTaskStatus(ctx, in, opts...)
}

// Search functionality
func (m *defaultTaskService) SearchTasks(ctx context.Context, in *SearchTasksRequest, opts ...grpc.CallOption) (*SearchTasksResponse, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.SearchTasks(ctx, in, opts...)
}

// Category operations
func (m *defaultTaskService) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.CreateCategory(ctx, in, opts...)
}

func (m *defaultTaskService) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.GetCategories(ctx, in, opts...)
}

func (m *defaultTaskService) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.UpdateCategory(ctx, in, opts...)
}

func (m *defaultTaskService) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.DeleteCategory(ctx, in, opts...)
}

// Statistics operations
func (m *defaultTaskService) GetStatsOverview(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsOverviewResponse, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.GetStatsOverview(ctx, in, opts...)
}

func (m *defaultTaskService) GetStatsCompletion(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsCompletionResponse, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.GetStatsCompletion(ctx, in, opts...)
}

// Batch operations
func (m *defaultTaskService) BatchUpdateStatus(ctx context.Context, in *BatchUpdateStatusRequest, opts ...grpc.CallOption) (*BatchUpdateStatusResponse, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.BatchUpdateStatus(ctx, in, opts...)
}

func (m *defaultTaskService) BatchDelete(ctx context.Context, in *BatchDeleteRequest, opts ...grpc.CallOption) (*BatchDeleteResponse, error) {
	client := task.NewTaskServiceClient(m.cli.Conn())
	return client.BatchDelete(ctx, in, opts...)
}
